#Define JWT manualmente
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg1ZDgwYjNkNTk1YjAxN2U0NzcxYWIiLCJpYXQiOjE3NzA0NjcxMDYsImV4cCI6MTc3MDQ3NDMwNn0.SzdV41sHYQMbTHS8Nyf3jMMHZeI7MuFrMxZVB6oPhdA
Authorization: Bearer {{JWT}}

###

GET https://localhost:4000/api/v1/datosAvanzados/stats HTTP/1.1
Authorization: Bearer {{JWT}}

###

GET https://localhost:4000/api/v1/datosAvanzados/6987336869864d28f95282db HTTP/1.1
Authorization: Bearer {{JWT}}

###
POST https://localhost:4000/api/v1/datosAvanzados HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "presion": 76,
    "indiceUV": 9,
    "indicePolen": 65,
    "sonda": "698723b2b26a19e008a5dc19",
    "fechaMedicion": "2025-11-02",
    "horaMedicion": "13:59"
}

###
PUT https://localhost:4000/api/v1/datosAvanzados/698739608575e6f96082fa1c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "presion": "50",
    "indiceUV": "3",
    "indicePolen": "57",
    "sonda": "698723b2b26a19e008a5dc19",
    "fechaMedicion": "2025-10-02",
    "horaMedicion": "17:00"
}

###
DELETE https://localhost:4000/api/v1/datosAvanzados/6987336869864d28f95282db HTTP/1.1
Authorization: Bearer {{JWT}}

###