#Define JWT manualmente
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg1ZDgwYjNkNTk1YjAxN2U0NzcxYWIiLCJpYXQiOjE3NzA0NjQxMjIsImV4cCI6MTc3MDQ3MTMyMn0.5PwesxnKb9fc0R7k59ee-gZEm7236fq8-LpmIWAgoZA

GET https://localhost:4000/api/v1/datosCalidadAire HTTP/1.1
Authorization: Bearer {{JWT}}

###

GET https://localhost:4000/api/v1/datosCalidadAire/stats HTTP/1.1
Authorization: Bearer {{JWT}}

###

GET https://localhost:4000/api/v1/datosCalidadAire/6907c7b7fabf4e99baf43549 HTTP/1.1
Authorization: Bearer {{JWT}}

###
POST https://localhost:4000/api/v1/datosCalidadAire HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "indiceCalidad": 25,
    "ozono_ppb": 13,
    "particulasPequenas_ugm3": 34,
    "particulasGrandes_ugm3": 54,
    "dioxidoNitrogeno_ppb": 23,
    "monoxidoCarbono_ppb": 43,
    "dioxidoAzufre_ppb": 56,
    "sonda": "695e36d85b8b7515a969f0c7",
    "fechaMedicion": "2025-11-02",
    "horaMedicion": "13:59"
}

###
PUT https://localhost:4000/api/v1/datosCalidadAire/6907c7b7fabf4e99baf43549 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "indiceCalidad": 45,
    "ozono_ppb": 76,
    "particulasPequenas_ugm3": 100,
    "particulasGrandes_ugm3": 54,
    "dioxidoNitrogeno_ppb": 23,
    "monoxidoCarbono_ppb": 43,
    "dioxidoAzufre_ppb": 56,
    "sonda": "695e36d85b8b7515a969f0c7",
    "fechaMedicion": "2025-10-02",
    "horaMedicion": "17:00"
}

###
DELETE https://localhost:4000/api/v1/datosCalidadAire/6907c7b7fabf4e99baf43549 HTTP/1.1
Authorization: Bearer {{JWT}}

###